#!python
from setuptools import setup, find_packages

setup(name='z3c.formwidget.traverser',
      version='0.1',
      author = "Zope Community",
      author_email = "zope3-dev@zope.org",
      description = "A widget traverser for z3c.form.",
      long_description=open('README.txt').read(),
      license = "ZPL 2.1",
      keywords = "zope zope3 z3c.form",
      url='http://svn.zope.org/z3c.formwidget.traverser',
      zip_safe=False,
      packages=find_packages('src'),
      include_package_data=True,
      package_dir = {'':'src'},
      namespace_packages=['z3c', 'z3c.formwidget'],
      extras_require = dict(
        test = [
          'zope.app.container',
          'zope.testing',
          'z3c.coverage',
          'z3c.template',
          'zope.app.i18n',
          ],
        adding = ['zope.app.container'],
      ),
      install_requires = [
          'setuptools',
          'zope.app.pagetemplate',
          'zope.app.testing',
          'zope.component',
          'zope.configuration',
          'zope.event',
          'zope.i18n',
          'zope.i18nmessageid',
          'zope.interface',
          'zope.lifecycleevent',
          'zope.location',
          'zope.pagetemplate',
          'zope.publisher',
          'zope.schema',
          'zope.security',
          ],
      classifiers = ['Development Status :: 4 - Alpha',
                     'Environment :: Web Environment',
                     'Framework :: Zope3',
                     'Intended Audience :: Developers',
                     'License :: OSI Approved :: Zope Public License',
                     'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
                     'Programming Language :: Python',
                     'Topic :: Software Development :: Libraries :: Python Modules',
                     ],
      )
