#!/bin/sh

# Actions executed (via commitinfo) at the start of a commit.

# The script is invoked within the directory of the checkin.  $CVSROOT 
# is the repository root dir.

# Expected Arguments:
#  $1  - the directory of the corresponding cvs repository for the checkins.
#  $2- - the names of the files being committed, from the working directory.

SCRIPT="$0"
REPOSITORY="$1"; shift
FILES="$@"

#echo script: $SCRIPT repo: $REPOSITORY files: $FILES

pwd
set -x
/bin/chmod g+w $FILES
