#!/bin/sh

# Actions executed (via commitinfo) at the start of a commit.

# The script is invoked within the directory of the checkin.
#  $1 - the directory of the corresponding cvs repository for the checkins.
#  $2- - the names of the files being committed, from the working directory.
#  $CVSROOT - 

WD=`pwd`
SCRIPT="$0"
REPOSITORY="$1"; shift
FILES="$@"

exec 1>>/tmp/log-precommit_actions

set -x
/bin/chmod g+w $FILES
