from setuptools import setup, find_packages

setup(
    name = 'z3c.optionstorage',
    version = '0.1.3',
    author = 'Zope Corporation and Contributors',
    author_email = 'zope3-dev@zope.org',
    description = '',
    license = 'ZPL 2.1',
    namespace_packages=['z3c'],
    packages = find_packages('src'),
    package_dir = {'': 'src'},
    include_package_data = True,
    install_requires = ['setuptools',
                        'ZODB3',
                        'zope.annotation',
                        'zope.configuration', 
                        'zope.deprecation', 
                        'zope.i18n',
                        'zope.interface',
                        'zope.proxy',
                        'zope.app.schema',
                        'zope.schema',
                        'zope.security',
                        'zope.app.pagetemplate',
                        'zope.app.publisher',
                        'zope.app.form',
                        'zope.app.zapi'],
    dependency_links=['http://download.zope.org/distribution/'],
    zip_safe = False,
    )
