from setuptools import setup, find_packages

setup(
    name = 'zope.app.workflow',
    version = '0.1',
    author = 'Zope Corporation and Contributors',
    author_email = 'zope3-dev@zope.org',
    description = '',
    license = 'ZPL 2.1',

    packages = find_packages('src'),
    namespace_packages = ['zope', 'zope.app'],
    package_dir = {'': 'src'},
    extras_require=dict(test=['zope.app.testing',
                              'zope.app.zcmlfiles',
                              'zope.app.file',
                              'zope.app.securitypolicy']),
    install_requires = ['setuptools',
                        'ZODB3',
                        'zope.component',
                        'zope.interface',
                        'zope.lifecycleevent',
                        'zope.app.container',
                        'zope.tales',
                        'zope.security',
                        'zope.schema',
                        'zope.security',
                        'zope.proxy',
                        'zope.traversing',
                        'zope.event',
                        'zope.app.i18n',
                        'zope.configuration',
                        'zope.dublincore',
                        'zope.app.pagetemplate',
                        'zope.app.security',
                        'zope.publisher',
                        'zope.app.form'],
    zip_safe = False,
    )
