from setuptools import setup, find_packages

setup(
    name = "z3c.imagewidget",
    version = "0.1dev",
    author = "Zope Contributors",
    author_email = "zope3-dev@zope.org",
    description = "Image Widget",
    license = "ZPL 2.1",
    keywords = "zope3 image widget",
    url = 'http://svn.zope.org/z3c.imagewidget',
    classifiers = [
        'Development Status :: 3 - Alpha',
        "License :: OSI Approved :: Zope Public License",
        "Framework :: Zope :: UI"],
    packages = find_packages('src'),
    include_package_data = True,
    package_dir = {'':'src'},
    namespace_packages = ['z3c'],
    zip_safe = False,
    extras_require = dict(test=['zope.component',
                                'zope.app.testing',
                                'zope.annotation',
                                'zope.testing',
                               ]),
    install_requires = ['setuptools',
                        'z3c.image',
                        'z3c.sessionwidget',
                        'zope.app.component',
                        'zope.app.file',
                        'zope.app.form',
                        'zope.app.i18n',
                        'zope.app.pagetemplate',
                        'zope.dublincore',
                        'zope.event',
                        'zope.formlib',
                        'zope.interface',
                        'zope.lifecycleevent',
                        'zope.publisher',
                        'zope.schema',
                        'zope.traversing',
                        ],
)
