from setuptools import setup, find_packages

setup(
    name="zc.comment",
    version="0.1dev",
    packages=find_packages('src'),
    package_dir={'':'src'},
    namespace_packages=['zc'],
    include_package_data=True,
    install_requires = [ 'setuptools',
                         'zope.interface',
                         'zope.component',
                         'zope.schema',
                         'zope.cachedescriptors',
                         'zope.app.zapi',
                         'zope.app.pagetemplate',
                         'zope.formlib',
                         'zc.table',
                         'zope.app.form',
                         'zope.annotation',
                         'zope.lifecycleevent',
                         'zc.security',
                         'zope.i18nmessageid',
                         'zope.event',
                         'zope.publisher',
                         'zope.app.zcmlfiles',
                         ],
    extras_require = dict( test=[ 'zope.app.testing',
                                  'zope.testbrowser',
                                  'zope.security',
                                  'pytz',
                                  'ZODB3',
                                  'zope.testing',
                                  ]
                           ),
    zip_safe = False,
    )
