from hurry.resource import Library, Inclusion, ResourceSpec

yui = Library('yui')

yahoo = Inclusion([ResourceSpec(yui, "yahoo/yahoo.js")], debug="yahoo/yahoo-debug.js", minified="yahoo/yahoo-min.js")
event = Inclusion([ResourceSpec(yui, "event/event.js")], depends_on=[yahoo], debug="event/event-debug.js", minified="event/event-min.js")
dom = Inclusion([ResourceSpec(yui, "dom/dom.js")], depends_on=[yahoo], debug="dom/dom-debug.js", minified="dom/dom-min.js")
element = Inclusion([ResourceSpec(yui, "element/element-beta.js")], depends_on=[dom, event], debug="element/element-beta-debug.js", minified="element/element-beta-min.js")
dragdrop = Inclusion([ResourceSpec(yui, "dragdrop/dragdrop.js")], depends_on=[dom, event], debug="dragdrop/dragdrop-debug.js", minified="dragdrop/dragdrop-min.js")
containercore = Inclusion([ResourceSpec(yui, "container/container_core.js")], depends_on=[dom, event], debug="container/container_core-debug.js", minified="container/container_core-min.js")
history = Inclusion([ResourceSpec(yui, "history/history.js")], depends_on=[event], debug="history/history-debug.js", minified="history/history-min.js")
treeview = Inclusion([ResourceSpec(yui, "treeview/treeview.js")], depends_on=[event], debug="treeview/treeview-debug.js", minified="treeview/treeview-min.js")
datasource = Inclusion([ResourceSpec(yui, "datasource/datasource-beta.js")], depends_on=[event], debug="datasource/datasource-beta-debug.js", minified="datasource/datasource-beta-min.js")
connection = Inclusion([ResourceSpec(yui, "connection/connection.js")], depends_on=[event], debug="connection/connection-debug.js", minified="connection/connection-min.js")
autocomplete = Inclusion([ResourceSpec(yui, "autocomplete/autocomplete.js")], depends_on=[dom, event], debug="autocomplete/autocomplete-debug.js", minified="autocomplete/autocomplete-min.js")
fonts = Inclusion([ResourceSpec(yui, "fonts/fonts.css")], minified="fonts/fonts-min.css")
button = Inclusion([ResourceSpec(yui, "button/button.js")], depends_on=[element], debug="button/button-debug.js", minified="button/button-min.js")
tabview = Inclusion([ResourceSpec(yui, "tabview/tabview.js")], depends_on=[element], debug="tabview/tabview-debug.js", minified="tabview/tabview-min.js")
yuiloader = Inclusion([ResourceSpec(yui, "yuiloader/yuiloader-beta.js")], debug="yuiloader/yuiloader-beta-debug.js", minified="yuiloader/yuiloader-beta-min.js")
reset = Inclusion([ResourceSpec(yui, "reset/reset.css")], minified="reset/reset-min.css")
simpleeditor = Inclusion([ResourceSpec(yui, "editor/simpleeditor-beta.js")], depends_on=[element], debug="editor/simpleeditor-beta-debug.js", minified="editor/simpleeditor-beta-min.js")
resize = Inclusion([ResourceSpec(yui, "resize/resize-beta.js")], depends_on=[dom, event, dragdrop, element], debug="resize/resize-beta-debug.js", minified="resize/resize-beta-min.js")
datatable = Inclusion([ResourceSpec(yui, "datatable/datatable-beta.js")], depends_on=[element, datasource], debug="datatable/datatable-beta-debug.js", minified="datatable/datatable-beta-min.js")
profilerviewer = Inclusion([ResourceSpec(yui, "profilerviewer/profilerviewer-beta.js")], depends_on=[profiler, yuiloader, element], debug="profilerviewer/profilerviewer-beta-debug.js", minified="profilerviewer/profilerviewer-beta-min.js")
layout = Inclusion([ResourceSpec(yui, "layout/layout-beta.js")], depends_on=[dom, event, element], debug="layout/layout-beta-debug.js", minified="layout/layout-beta-min.js")
uploader = Inclusion([ResourceSpec(yui, "uploader/uploader-experimental.js")], depends_on=[element], debug="uploader/uploader-experimental-debug.js", minified="uploader/uploader-experimental-min.js")
cookie = Inclusion([ResourceSpec(yui, "cookie/cookie-beta.js")], depends_on=[yahoo], debug="cookie/cookie-beta-debug.js", minified="cookie/cookie-beta-min.js")
base = Inclusion([ResourceSpec(yui, "base/base.css")], minified="base/base-min.css")
slider = Inclusion([ResourceSpec(yui, "slider/slider.js")], depends_on=[dragdrop], debug="slider/slider-debug.js", minified="slider/slider-min.js")
selector = Inclusion([ResourceSpec(yui, "selector/selector-beta.js")], depends_on=[yahoo, dom], debug="selector/selector-beta-debug.js", minified="selector/selector-beta-min.js")
utilities = Inclusion([ResourceSpec(yui, "utilities/utilities.js")], debug="utilities/utilities-debug.js", minified="utilities/utilities-min.js")
yuitest = Inclusion([ResourceSpec(yui, "yuitest/yuitest.js")], depends_on=[logger], debug="yuitest/yuitest-debug.js", minified="yuitest/yuitest-min.js")
yuiloader_dom_event = Inclusion([ResourceSpec(yui, "yuiloader-dom-event/yuiloader-dom-event.js")], debug="yuiloader-dom-event/yuiloader-dom-event-debug.js", minified="yuiloader-dom-event/yuiloader-dom-event-min.js")
get = Inclusion([ResourceSpec(yui, "get/get.js")], depends_on=[yahoo], debug="get/get-debug.js", minified="get/get-min.js")
colorpicker = Inclusion([ResourceSpec(yui, "colorpicker/colorpicker.js")], depends_on=[slider, element], debug="colorpicker/colorpicker-debug.js", minified="colorpicker/colorpicker-min.js")
logger = Inclusion([ResourceSpec(yui, "logger/logger.js")], depends_on=[event, dom], debug="logger/logger-debug.js", minified="logger/logger-min.js")
imagecropper = Inclusion([ResourceSpec(yui, "imagecropper/imagecropper-beta.js")], depends_on=[dom, event, dragdrop, element, resize], debug="imagecropper/imagecropper-beta-debug.js", minified="imagecropper/imagecropper-beta-min.js")
editor = Inclusion([ResourceSpec(yui, "editor/editor-beta.js")], depends_on=[menu, element, button], debug="editor/editor-beta-debug.js", minified="editor/editor-beta-min.js")
animation = Inclusion([ResourceSpec(yui, "animation/animation.js")], depends_on=[dom, event], debug="animation/animation-debug.js", minified="animation/animation-min.js")
json = Inclusion([ResourceSpec(yui, "json/json.js")], depends_on=[yahoo], debug="json/json-debug.js", minified="json/json-min.js")
charts = Inclusion([ResourceSpec(yui, "charts/charts-experimental.js")], depends_on=[element, json, datasource], debug="charts/charts-experimental-debug.js", minified="charts/charts-experimental-min.js")
menu = Inclusion([ResourceSpec(yui, "menu/menu.js")], depends_on=[containercore], debug="menu/menu-debug.js", minified="menu/menu-min.js")
reset_fonts_grids = Inclusion([ResourceSpec(yui, "reset-fonts-grids/reset-fonts-grids.css")], minified="reset-fonts-grids/reset-fonts-grids-min.css")
container = Inclusion([ResourceSpec(yui, "container/container.js")], depends_on=[dom, event], debug="container/container-debug.js", minified="container/container-min.js")
profiler = Inclusion([ResourceSpec(yui, "profiler/profiler-beta.js")], depends_on=[yahoo], debug="profiler/profiler-beta-debug.js", minified="profiler/profiler-beta-min.js")
calendar = Inclusion([ResourceSpec(yui, "calendar/calendar.js")], depends_on=[event, dom], debug="calendar/calendar-debug.js", minified="calendar/calendar-min.js")
imageloader = Inclusion([ResourceSpec(yui, "imageloader/imageloader.js")], depends_on=[event, dom], debug="imageloader/imageloader-debug.js", minified="imageloader/imageloader-min.js")
reset_fonts = Inclusion([ResourceSpec(yui, "reset-fonts/reset-fonts.css")], minified="reset-fonts/reset-fonts-min.css")
grids = Inclusion([ResourceSpec(yui, "grids/grids.css")], depends_on=[fonts], minified="grids/grids-min.css")
yahoo_dom_event = Inclusion([ResourceSpec(yui, "yahoo-dom-event/yahoo-dom-event.js")], debug="yahoo-dom-event/yahoo-dom-event-debug.js", minified="yahoo-dom-event/yahoo-dom-event-min.js")

