from setuptools import setup, find_packages

setup(name='z3c.zalchemy',
      version='0.2',
      author='Juergen Kartnaller',
      author_email='juergen.kartnaller@lovelysystems.com',
      url='https://svn.zope.org.repos/main',
      description="""SQLAlchemy integration into Zope 3""",
      license='ZPL 2.1',

      packages=find_packages('src'),
      package_dir = {'': 'src'},
      include_package_data = True,
      zip_safe=False,
      install_requires=['setuptools',
                        'SQLAlchemy',
                        'ZODB3',
                        'zope.component',
                        'zope.interface',
                        'zope.schema',
                        'zope.app.testing',
                        'zope.app.component',
                        'zope.app.keyreference<3.5dev',
                        'zope.app.container',
                        'zope.app.pagetemplate',
                       ],
      extras_require = dict(test=['pysqlite']))
